<%@ include file="/common/taglibs.jsp"%>

<style type="text/css">
@import url("${pageContext.request.contextPath}/plugins/bootstrap/css/bootstrap.min.css");
@import url("${pageContext.request.contextPath}/styles/newCss/pages/invoice.css");
 
 <% String browser = request.getHeader("user-agent");
 	   if (browser.indexOf("MSIE") != -1) { %>
	@import url("${pageContext.request.contextPath}/styles/newCss/pages/challanFirefox.css");
	<% } else if (browser.indexOf("Chrome") != -1) { %>
	@import url("${pageContext.request.contextPath}/styles/newCss/pages/challanChrome.css");
	<% } else if (browser.indexOf("Firefox") != -1) { %>
	@import url("${pageContext.request.contextPath}/styles/newCss/pages/challanFirefox.css");
	<% } else { %>
	@import url("${pageContext.request.contextPath}/styles/newCss/pages/challanFirefox.css");
	<% } %>
</style>
 
 <div style="width: 100%; padding: 10px;">
	<div style="width: 32%; float: left; border: 1px solid;margin: 5px;height: 94%;">
		<table class="footerDiv" style="width: 100%;">
			<tbody>
				<tr class="tabTRClass"><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td></tr>
				<tr class="tabTRClass">
					<td  style="width: 38%;">
						<label style="float:left ;"> <s:property value="academicYear.academicYear"/></label>
					</td>
					<td style="width: 33%;">
						<label style="float: left;"><b>BANK COPY</b></label></td>
					<td style="width: 33%;">
						<label style="float: right;"> <s:property value="viewStudentClassDetails.classAndSection"/></label>
					</td>
				</tr>
			</tbody>
		</table>
		<jsp:include page="/WEB-INF/pages/admin/reports/feeReciept/viewChallanaA4Reciept_209.jsp"></jsp:include>
		<table class="footerDiv" style="width: 100%;margin-top: -10px;">
			<tbody>
				<tr class="tabTRClass"><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td></tr>
				<tr class="tabTRClass">
					<td style="width: 50%;">
						<label style="float: left;"><b>&nbsp;</b></label></td>
					<td class="tabeAmountTd" style="width: 50%; font-size: 8px;">
						<label style="float: right;"> Generated By:<a id="myAnchor" href="http://www.Eazyschool.com" target="_blank">www.Eazyschool.com</a></label>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div style="width: 32%; float: left; border: 1px solid;margin: 5px;height: 94%;">
		<table class="footerDiv" style="width: 100%;">
			<tbody>
				<tr class="tabTRClass"><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td></tr>
				<tr class="tabTRClass">
					<td  style="width: 38%;">
						<label style="float:left ;"> <s:property value="academicYear.academicYear"/></label>
					</td>
					<td style="width: 33%;">
						<label style="float: left;"><b>SCHOOL COPY</b></label></td>
					<td style="width: 33%;">
						<label style="float: right;"> <s:property value="viewStudentClassDetails.classAndSection"/></label>
					</td>
				</tr>
			</tbody>
		</table>
		<jsp:include page="/WEB-INF/pages/admin/reports/feeReciept/viewChallanaA4Reciept_School_209.jsp"></jsp:include>
		 <table class="footerDiv" style="width: 100%;margin-top: -2px;">
			<tbody>
				<tr class="tabTRClass">
					<td style="width: 50%;">
						<label style="float: left;"><b>&nbsp;</b></label></td>
					<td class="tabeAmountTd" style="width: 50%; font-size: 8px;">
						<label style="float: right;"> Generated By:<a id="myAnchor" href="http://www.Eazyschool.com" target="_blank">www.Eazyschool.com</a></label>
					</td>
				</tr>
			</tbody>
		</table> 
	</div>
	<div style="width: 32%;float: left;border: 1px solid;margin: 5px;height: 94%;">
		<table class="footerDiv" style="width: 100%;">
			<tbody>
				<tr class="tabTRClass"><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td><td  style="width: 33%;">&nbsp;</td></tr>
				<tr class="tabTRClass">
					<td  style="width: 38%;">
						<label style="float:left ;"> <s:property value="academicYear.academicYear"/></label>
					</td>
					<td style="width: 33%;">
						<label style="float: left;"><b>PARENT'S COPY</b></label></td>
					<td style="width: 33%;">
						<label style="float: right;"> <s:property value="viewStudentClassDetails.classAndSection"/></label>
					</td>
				</tr>
			</tbody>
		</table>
		<jsp:include page="/WEB-INF/pages/admin/reports/feeReciept/viewChallanaA4Reciept_School_209.jsp"></jsp:include>
		  <table class="footerDiv" style="width: 100%;margin-top: -2px;">
			<tbody>
				
				<tr class="tabTRClass">
					<td style="width: 50%;">
						<label style="float: left;"><b>&nbsp;</b></label></td>
					<td class="tabeAmountTd" style="width: 50%; font-size: 8px;">
						<label style="float: right;"> Generated By:<a id="myAnchor" href="http://www.Eazyschool.com" target="_blank">www.Eazyschool.com</a></label>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div style="width: 51%;float: right;" id="pageToPrint">
	</div>
</div>
  
<script  type="text/javascript">
var newElement = document.createElement("a");
var html="Print";
newElement.setAttribute('id', "printButton");
newElement.setAttribute('href', "javascript:window.print();");
newElement.innerHTML = html;
document.getElementById('pageToPrint').appendChild(newElement);
 
</script>
<style type="text/css">
page {
  background: white;
  display: block;
  margin: 0 auto;
  margin-bottom: 0.5cm;
  box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);
}
page[size="A3"] {
  width: 25cm;
  height: 27cm;
}
page[size="A4"] {  
  width: 21cm;
  height: 22cm; 
}

page[size="A5"] {
  width: 14.8cm;
  height: 19cm;
}

page[size="A6"] {
  width: 10.5cm;
  height: 13.8cm;
}
page[size="A3"][layout="portrait"] {
  width: 42cm;
  height: 24cm;  
}
page[size="A4"][layout="portrait"] {
  width: 25cm;
  height: 21cm;  
}
page[size="A5"][layout="portrait"] {
  width: 21cm;
  height: 13.8cm;  
}

page[size="A6"] [layout="portrait"] {
  width: 52cm;
  height: 13.8cm;
}
.pageHeader1{
 border: 1px solid #222;
}
.table{
	margin-bottom:0px;
}
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
{
padding:0px;
}
span.receptFontSubHeaderRow{
	font-size: 12px;
	text-align: center;
	color:0000FF;
	float: right;
	width: 150px;
}
.reasonFont{
	font-size: 10px;
	 text-align: left;
	  padding: 0px 5px 0px 5px;
}
.parentCopy{
  color:#c0c5ce;
  text-align: center;
}
.generatedBy{
 float:right;
 font-size: 10px;
}
.schoolName{
	color:#006400;
}
.orgHeader{
	color:#006400;
	font-size: 16px;
}
hr {
    border-color: #222 -moz-use-text-color -moz-use-text-color;
    border-width: 1px 0 0;
}
div.dotted {
	border-top-style: dotted;
}
.discount{
	color:#ff8a9b;
	font-size: 12px;
}
 
</style>
<style type="text/css" media="print">
    @media print{
    a#printButton {
       display:none !important;
    }
    body:blank{
      display: none;
    }
    .pageToPrint+.pageToPrint {
       page-break-before: always;
    }
}
</style>



 