package com.urt.persistence.model.common;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.urt.persistence.model.base.PersistentObject;



/**
 * AbstractState generated by MyEclipse - Hibernate Tools
 */
@Entity
@Table(name = "academicYearTimings")
public class AcademicYearTimings  extends PersistentObject {

    private static final long serialVersionUID = -9190968485277417762L;
    private long academicYearId;
    private String status;
    private long classId;
    private String weekDay;
    protected String startTime;
    protected String endTime;
    protected String morningBreakStartTime;
    protected String morningBreakEndTime;
    protected String eveningBreakStartTime;
    protected String eveningBreakEndTime;
    protected String lunchStartTime;
    protected String lunchEndTime;
    
    
    @Column(name="academicYearId", nullable=false, length=10, unique=false)
	public long getAcademicYearId() {
		return academicYearId;
	}

	public void setAcademicYearId(long academicYearId) {
		this.academicYearId = academicYearId;
	}
	
	@Column(name = "status", nullable = true, length = 2,columnDefinition="varchar(2) default 'ST'")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	 @Column(name="classId", nullable=false, length=10, unique=false, columnDefinition="int default 0")
	public long getClassId() {
		return classId;
	}

	public void setClassId(long classId) {
		this.classId = classId;
	}

 @Column(name = "weekDay", nullable = true, length = 20,columnDefinition="varchar(20)")
	public String getWeekDay() {
		return weekDay;
	}

	public void setWeekDay(String weekDay) {
		this.weekDay = weekDay;
	}
	
	@Column(name = "startTime", nullable = true, length = 10,unique=false)
	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}
	
	@Column(name = "endTime", nullable = true, length = 10,unique=false)
	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "morningBreakStartTime", nullable = true, length = 10,unique=false)
	public String getMorningBreakStartTime() {
		return morningBreakStartTime;
	}

	public void setMorningBreakStartTime(String morningBreakStartTime) {
		this.morningBreakStartTime = morningBreakStartTime;
	}

	@Column(name = "morningBreakEndTime", nullable = true, length = 10,unique=false)
	public String getMorningBreakEndTime() {
		return morningBreakEndTime;
	}

	public void setMorningBreakEndTime(String morningBreakEndTime) {
		this.morningBreakEndTime = morningBreakEndTime;
	}

	@Column(name = "eveningBreakStartTime", nullable = true, length = 10,unique=false)
	public String getEveningBreakStartTime() {
		return eveningBreakStartTime;
	}

	public void setEveningBreakStartTime(String eveningBreakStartTime) {
		this.eveningBreakStartTime = eveningBreakStartTime;
	}

	@Column(name = "eveningBreakEndTime", nullable = true, length = 10,unique=false)
	public String getEveningBreakEndTime() {
		return eveningBreakEndTime;
	}

	public void setEveningBreakEndTime(String eveningBreakEndTime) {
		this.eveningBreakEndTime = eveningBreakEndTime;
	}

	@Column(name = "lunchStartTime", nullable = true, length = 10,unique=false)
	public String getLunchStartTime() {
		return lunchStartTime;
	}

	public void setLunchStartTime(String lunchStartTime) {
		this.lunchStartTime = lunchStartTime;
	}

	public String getLunchEndTime() {
		return lunchEndTime;
	}

	public void setLunchEndTime(String lunchEndTime) {
		this.lunchEndTime = lunchEndTime;
	}

	/**
     * @see java.lang.Object#hashCode()
     */
    public int hashCode() {
        return new HashCodeBuilder(-465592447, 1546771509).append(
                this.status).append(this.status).toHashCode();
    }

    /**
     * @see java.lang.Object#equals(Object)
     */
    public boolean equals(Object object) {
        if (!(object instanceof AcademicYearTimings)) {
            return false;
        }
        AcademicYearTimings rhs = (AcademicYearTimings) object;
        return new EqualsBuilder().append(this.status, rhs.status)
                .append(this.status, rhs.status).isEquals();
    }

    /**
     * @see java.lang.Object#toString()
     */
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
                .append("id", this.getId())
                //.append("stateCode",
                .append("stateCode",
                        this.status).append("Status", this.status)
                .toString();
    }

    /**
     * @see java.lang.Comparable#compareTo(Object)
     */
    public int compareTo(Object object) {
    	AcademicYearTimings myClass = (AcademicYearTimings) object;
        return new CompareToBuilder().append(this.status, myClass.status)
                .toComparison();
    }

	
}