package com.urt.persistence.model.common;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.churchgroup.util.date.DateFormatter;
import com.urt.persistence.model.base.PersistentObject;



/**
 * AbstractState generated by MyEclipse - Hibernate Tools
 */
@Entity
@Table(name = "feedBackSettings")
public class FeedBackSettings  extends PersistentObject {

    private static final long serialVersionUID = -9190968485277417762L;
    private String status;
    private long custId;
    private Date startDate;
    private Date endDate;
    protected int attendancePercentage;
    private AcademicYear academicYear;
    
    @OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="academicYearId") 
	public AcademicYear getAcademicYear() {
		return academicYear;
	}
	public void setAcademicYear(AcademicYear academicYear) {
		this.academicYear = academicYear;
	}
	
    @Column(name = "status", nullable = true, length = 1,columnDefinition="char(1) default 'A'")
    public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public long getCustId() {
		return custId;
	}
	public void setCustId(long custId) {
		this.custId = custId;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public int getAttendancePercentage() {
		return attendancePercentage;
	}
	public void setAttendancePercentage(int attendancePercentage) {
		this.attendancePercentage = attendancePercentage;
	}
	@Override
	public int compareTo(Object object) {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}
	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "";
	}
	@Transient
	public String getStartDateStr() {
		return DateFormatter.formatDate(DateFormatter.ddMMMyyyy_PATTERN1, this.getStartDate());
	}
	
	@Transient
	public String getEndDateStr() {
		return DateFormatter.formatDate(DateFormatter.ddMMMyyyy_PATTERN1, this.getEndDate());
	}
	
	@Transient
	public String getStartDateFormet() {
		return DateFormatter.formatDate(DateFormatter.MMDDYYYY_PATTERN, this.getStartDate());
	}
	@Transient
	public String getEndDateFormet() {
		return DateFormatter.formatDate(DateFormatter.MMDDYYYY_PATTERN, this.getEndDate());
	}
	
  
}