package com.urt.persistence.model.study;

import java.util.Comparator;

import com.churchgroup.util.string.StringFunctions;
 
/**
 * Study generated by MyEclipse Persistence Tools
 */
 
public class TitleComparator implements Comparator {
 
    public int compare(Object study1, Object study2) {
 
        // parameter are of type Object, so we have to downcast it to Employee
        // objects
 
        String study1Title = ((StudySubject) study1).getName();
 
        String study2Title = ((StudySubject) study2).getDescription();
 
        if (!StringFunctions.isNullOrEmpty(study1Title) && !StringFunctions.isNullOrEmpty(study2Title))
        {
            return study1Title.compareToIgnoreCase(study2Title);
        }
        return 0;
    }
}