<%@ include file="/common/taglibs.jsp"%>
<style type="text/css">
@import url("${pageContext.request.contextPath}/plugins/bootstrap/css/bootstrap.min.css");
@import url("${pageContext.request.contextPath}/styles/newCss/pages/invoice.css");
/*@media print {
	.header, .hide { visibility: hidden }
}*/
@media screen and projection {
   a { display:inline; }
}
</style>
<div style="width: 100%; padding: 10px;">
	<div style="width: 49%; float: left; border: 1px solid">
		<jsp:include page="/WEB-INF/pages/admin/reports/popupStudentAdmissionRecieptDetails.jsp"></jsp:include>
		<div style="text-align: center;width:160px;">
			<b>SCHOOL COPY</b>
		</div>
		<div style="float:right;width:282px;">
				Generated By:<a id="myAnchor" href="http://www.Eazyschool.com" target="_blank">www.Eazyschool.com</a>
		</div>
	</div>
<div style="width: 49%;float: right;border: 1px solid;">
    <jsp:include page="/WEB-INF/pages/admin/reports/popupStudentAdmissionRecieptDetails.jsp"></jsp:include>
	<div style="text-align: center;width:130px;">
		<b>PARENT'S COPY</b>
	</div>
	<div style="float:right;width:282px;">
		Generated By:<a id="myAnchor" href="http://www.Eazyschool.com" target="_blank">www.Eazyschool.com</a>
	</div>
</div>
</div>
